Controllers/CompanyController.cs
using Bulky.data.data;
using Bulky.models;
using Microsoft.AspNetCore.Mvc;
using Bulky.data.Irepository.Repository;
using Bulky.data.Irepository;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace BlukyWeb.Controllers
{
    public class CompanyController : Controller
    {
		        
        //private readonly AppDbContext _context;
        private readonly IunitOfWork _unitofwork;
        public CompanyController(IunitOfWork iunitOfWork)
        {
			//_context = db;
			_unitofwork = iunitOfWork;
			

        }
        public IActionResult Index()
        {

			//List<Category> objcategoryList = _context.categories.ToList();
			List<Company> objCompanyList = _unitofwork.Company.GetAll().ToList();
           
            return View(objCompanyList);
        }
        public IActionResult Create()
        {
			return View(new Company());
        }
		
		public IActionResult Editss(int Id)
		{
			var companyobj = _unitofwork.Company.Get(u =>u.Id==Id);
			
			return View(companyobj);

           




        }

		// HTTP POST action to handle the edit form submission
		[HttpPost]
		
		public IActionResult Editss(Company model)
		{
            

           
               
          
			_unitofwork.Company.Update(model);
			
		   _unitofwork.Save();
			TempData["success"] = "category edited succesfully";

					// Redirect to the index action (list of categories) upon successful update
		return RedirectToAction("Index");
				
				
			

			
			
		}
		[HttpPost]
		public IActionResult Create(Company obj)
		{
			
				
           
                _unitofwork.Company.Add(obj);
			
				_unitofwork.Save();
				//_context.SaveChanges();
				TempData["success"] = "category create succesfully";
				return RedirectToAction("Index");
		}
		public IActionResult Delete(int Id)
		{
			var categoryToDelete =_unitofwork.Company.Get(u => u.Id==Id);
            if (categoryToDelete == null)
			{
				return NotFound();
			}
			

			return View(categoryToDelete);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(int Id)
		{
			var categoryToDelete =_unitofwork.Company.Get(u => u.Id == Id);
            if (categoryToDelete == null)
			{
				return NotFound();
			}

			_unitofwork.Company.Remove(categoryToDelete);
			_unitofwork.Save();
			//

			return RedirectToAction("Index");
		}

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> objcategoryList = _unitofwork.Company.GetAll().ToList();
            return Json(new { data = objcategoryList });
        }
        #endregion


    }
}

Controllers/OrderController.cs
using Bulky.data.Irepository;
using Bulky.models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace BlukyWeb.Controllers
{
    public class OrderController : Controller
    {
        private readonly IunitOfWork _unitofwork;

        public OrderController(IunitOfWork unitofwork)
        {
            _unitofwork = unitofwork;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll(string status)
        {
            List<OrderHeader> objcategoryList = _unitofwork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();

            // Apply filtering based on status, if provided
            switch (status)
            {
                case "pending":
                    objcategoryList = objcategoryList.Where(o => o.OrderStatus == "Not Approved").ToList();
                    break;
                case "completed":
                    objcategoryList = objcategoryList.Where(o => o.OrderStatus == "Approved").ToList();
                    break;
                case "approved":
                    objcategoryList = objcategoryList.Where(o => o.OrderStatus == "Approved").ToList();
                    break;
                case "all":
                    // No filtering needed for "all"
                    break;
                default:
                    // Handle other cases as needed
                    break;
            }

            return Json(new { data = objcategoryList });
        }

        #endregion
    }
}

Controllers/ProductController.cs
using Bulky.data.data;
using Bulky.models;
using Microsoft.AspNetCore.Mvc;
using Bulky.data.Irepository.Repository;
using Bulky.data.Irepository;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace BlukyWeb.Controllers
{
    public class ProductController : Controller
    {
		private readonly IWebHostEnvironment _environment;	
        
        //private readonly AppDbContext _context;
        private readonly IunitOfWork _unitofwork;
        public ProductController(IunitOfWork iunitOfWork,IWebHostEnvironment webHostEnvironment)
        {
			//_context = db;
			_unitofwork = iunitOfWork;
			_environment=webHostEnvironment;

        }
        public IActionResult Index()
        {
			
			//List<Category> objcategoryList = _context.categories.ToList();
			List<Product> objcategoryList = _unitofwork.Product.GetAll(includeProperties:"Category").ToList();
           
            return View(objcategoryList);
        }
        public IActionResult Create()
        {
            IEnumerable<SelectListItem> CategoryList = _unitofwork.Category.GetAll().ToList().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
			ViewBag.CategoryList = CategoryList;	
            return View();
        }
		
		public IActionResult Editss(int id)
		{
            IEnumerable<SelectListItem> CategoryList = _unitofwork.Category.GetAll().ToList().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            ViewBag.CategoryList = CategoryList;

            //var categoryfromdbs = _context.categories.Find(id);
            var categoryFromDb=_unitofwork.Product.Get(u=>u.Id == id);

			// Check if the category exists
			//if (categoryfromdb == null)
			//{
				
			//	return NotFound();
			//}

			
			return View(categoryFromDb);
		}

		// HTTP POST action to handle the edit form submission
		[HttpPost]
		
		public IActionResult Editss(Product model, IFormFile? file)
		{
            //string wwwRooTPath = _environment.WebRootPath;
            //if (file != null)
            //{
            //    string fileName = Guid.NewGuid().ToString();
            //    string productPath = Path.Combine(wwwRooTPath, @"images\product");
            //    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
            //    {
            //        file.CopyTo(fileStream);
            //    }
            //    model.ImageUrl = "/images/product/" + fileName;

            //}

            string wwwRootPath = _environment.WebRootPath;
            if (file != null && file.Length > 0)
            {
                // Generate a unique file name with .jpeg extension
                string fileName = Guid.NewGuid().ToString() + ".jpeg";

                // Construct the full path where the file will be saved
                string productPath = Path.Combine(wwwRootPath, "images", "product");
                string filePath = Path.Combine(productPath, fileName);

                // Ensure the product directory exists; create it if it doesn't
                Directory.CreateDirectory(productPath);

                // Copy the uploaded file to the specified path
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }

                // Set the model's ImageUrl property to the relative path of the saved image
                model.ImageUrl = "/images/product/" + fileName;
            }
			_unitofwork.Product.Update(model);
			
					_unitofwork.Save();
				TempData["success"] = "category edited succesfully";

					// Redirect to the index action (list of categories) upon successful update
					return RedirectToAction("Index");
				
				
			

			
			
		}
		[HttpPost]
		public IActionResult Create(Product obj,IFormFile? file)
		{
			
				string wwwRooTPath = _environment.WebRootPath;
				if (file != null) {
					string fileName=Guid.NewGuid().ToString();
					string productPath = Path.Combine(wwwRooTPath, @"images\product");
					using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
					{
						file.CopyTo(fileStream);
					}
                obj.ImageUrl = "/images/product/" + fileName;

            }
                //_context.categories.Add(obj);
                _unitofwork.Product.Add(obj);
			
				_unitofwork.Save();
				//_context.SaveChanges();
				TempData["success"] = "category create succesfully";
				return RedirectToAction("Index");
		}
		public IActionResult Delete(int Id)
		{
			var categoryToDelete =_unitofwork.Product.Get(u => u.Id==Id);
            if (categoryToDelete == null)
			{
				return NotFound();
			}
			

			return View(categoryToDelete);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(int Id)
		{
			var categoryToDelete =_unitofwork.Product.Get(u => u.Id == Id);
            if (categoryToDelete == null)
			{
				return NotFound();
			}

			_unitofwork.Product.Remove(categoryToDelete);
			_unitofwork.Save();
			//

			return RedirectToAction("Index");
		}
        #region API CALLS
        [HttpGet]
		public IActionResult GetAll()
		{
            List<Product> objcategoryList = _unitofwork.Product.GetAll(includeProperties: "Category").ToList();
			return Json(new { data = objcategoryList });
        }
		#endregion


	}
}

Controllers/UserController.cs
using Bulky.data.data;
using Bulky.models;
using Microsoft.AspNetCore.Mvc;
using Bulky.data.Irepository.Repository;
using Bulky.data.Irepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace BlukyWeb.Controllers
{
    public class UserController : Controller
    {
        private readonly AppDbContext _db;

        public UserController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> objcategoryList = _db.ApplicationUsers.Include(u=>u.Company).ToList();
            var userRoles = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();

            foreach (var user in objcategoryList)
            {
                var userRole = userRoles.FirstOrDefault(u => u.UserId == user.Id);
                if (userRole != null)
                {
                    var role = roles.FirstOrDefault(u => u.Id == userRole.RoleId);
                    if (role != null)
                    {
                        user.Role = role.Name;
                    }
                }

                if (user.Company == null)
                {
                    user.Company = new Company { Name = "He is not from company" };
                }
            }

            return Json(new { data = objcategoryList });
        }

        #endregion
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor IHttpContextAcessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlukyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlukyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlukyWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Company" asp-action="Index">Company</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Manage User</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Product" asp-action="index">Product</a>
                            </li>
                        }
                        @if (@IHttpContextAcessor.HttpContext.Session.GetInt32(SD.SessionCart) != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-cart"></i> &nbsp;
                                    (@IHttpContextAcessor.HttpContext.Session.GetInt32(SD.SessionCart))
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-cart"></i> &nbsp;(0)
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-center">
            made with <i class="bi bi-balloon-heart"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage advtemplate ai mentions tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss markdown',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.0.8/js/dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{<script src="~/lib/jquery/dist/jquery.min.js"></scRipt>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
	toastr.success('@TempData["success"]')
	</script>
}